# Generated by Django 2.0.6 on 2018-08-26 09:51

from django.conf import settings
import django.contrib.auth.mixins
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_main', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientConnection',
            fields=[
                ('name', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('rfid_tag', models.CharField(max_length=10, verbose_name='RFID')),
            ],
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('description', models.CharField(help_text='Insert short description here.', max_length=1000)),
                ('gimprove_system', models.BooleanField(default=False)),
                ('equipment_machine', models.ManyToManyField(blank=True, help_text='Necessary equipment for the exercise.', to='app_tracker.Equipment')),
            ],
        ),
        migrations.CreateModel(
            name='ExerciseUnit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('time_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('equipment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_tracker.Equipment')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_tracker.Exercise')),
            ],
            options={
                'ordering': ['-time_date'],
            },
        ),
        migrations.CreateModel(
            name='Muscle',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='MuscleGroup',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Set',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('date_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('repetitions', models.IntegerField()),
                ('weight', models.FloatField()),
                ('durations', models.TextField(max_length=1200)),
                ('auto_tracking', models.BooleanField(default=False)),
                ('last_update', models.DateTimeField(default=django.utils.timezone.now)),
                ('exercise_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_tracker.ExerciseUnit')),
            ],
            options={
                'ordering': ['-date_time'],
            },
        ),
        migrations.CreateModel(
            name='TrainUnit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('start_time_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_time_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('date', models.DateField()),
            ],
            options={
                'ordering': ['-start_time_date'],
            },
            bases=(models.Model, django.contrib.auth.mixins.LoginRequiredMixin),
        ),
        migrations.CreateModel(
            name='UserTrackingProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_pr_active_set', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app_tracker.Set')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_main.UserProfile')),
            ],
        ),
        migrations.AddField(
            model_name='trainunit',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_tracker.UserTrackingProfile'),
        ),
        migrations.AddField(
            model_name='muscle',
            name='muscle_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app_tracker.MuscleGroup'),
        ),
        migrations.AddField(
            model_name='exerciseunit',
            name='train_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_tracker.TrainUnit'),
        ),
        migrations.AddField(
            model_name='exercise',
            name='muscles',
            field=models.ManyToManyField(help_text='Muscles trained by the exercise.', to='app_tracker.Muscle'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='exercises',
            field=models.ManyToManyField(to='app_tracker.Exercise'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='gym',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='gym', to='app_main.GymProfile'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
    ]
