# Generated by Django 2.0.1 on 2018-08-27 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_tracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='set',
            name='equipment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app_tracker.Equipment'),
        ),
        migrations.AddField(
            model_name='set',
            name='exercise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_tracker.Exercise'),
        ),
    ]
