# Generated by Django 2.0.1 on 2018-08-27 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_tracker', '0003_set_rfid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='set',
            name='exercise',
        ),
        migrations.AddField(
            model_name='set',
            name='exercise_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='set',
            name='exercise_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_tracker.ExerciseUnit'),
        ),
        migrations.AlterField(
            model_name='set',
            name='rfid',
            field=models.CharField(max_length=10),
        ),
    ]
