# Generated by Django 2.0.1 on 2018-08-27 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_tracker', '0004_auto_20180827_1952'),
    ]

    operations = [
        migrations.AddField(
            model_name='set',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
