# Generated by Django 2.0.1 on 2018-08-27 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_tracker', '0005_set_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='set',
            name='exercise_name',
        ),
        migrations.AddField(
            model_name='set',
            name='exercise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_tracker.Exercise'),
        ),
    ]
