# Generated by Django 2.0.1 on 2018-08-28 05:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_tracker', '0006_auto_20180827_2059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='set',
            name='exercise',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_tracker.Exercise'),
        ),
        migrations.AlterField(
            model_name='set',
            name='exercise_unit',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_tracker.ExerciseUnit'),
        ),
        migrations.AlterField(
            model_name='set',
            name='rfid',
            field=models.CharField(blank=True, default=None, max_length=10, null=True),
        ),
    ]
