# Generated by Django 2.0.6 on 2018-09-10 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_tracker', '0008_auto_20180910_1850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientconnection',
            name='user',
            field=models.CharField(max_length=10, verbose_name='user'),
        ),
    ]
