# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-10 17:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('description', models.CharField(help_text='Insert short description here.', max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='ExerciseUnit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('start_time_date', models.DateTimeField()),
                ('end_time_date', models.DateTimeField()),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.Exercise')),
            ],
        ),
        migrations.CreateModel(
            name='Muscle',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Set',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('date_time', models.DateTimeField()),
                ('repetitions', models.IntegerField()),
                ('exercise_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.ExerciseUnit')),
            ],
        ),
        migrations.CreateModel(
            name='TrainUnit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('start_time_date', models.DateTimeField()),
                ('end_time_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('date_of_birth', models.DateField()),
                ('training_units', models.ManyToManyField(related_name='_user_training_units_+', to='tracker.TrainUnit')),
            ],
            options={
                'ordering': ('last_name', 'first_name', 'date_of_birth'),
            },
        ),
        migrations.AddField(
            model_name='trainunit',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.User'),
        ),
        migrations.AddField(
            model_name='exerciseunit',
            name='train_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.TrainUnit'),
        ),
        migrations.AddField(
            model_name='exercise',
            name='muscles',
            field=models.ManyToManyField(help_text='Muscles trained by the exercise.', to='tracker.Muscle'),
        ),
    ]
