# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-19 17:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_auto_20171019_1830'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainunit',
            name='exercice_units',
            field=models.ManyToManyField(blank=True, null=True, related_name='_trainunit_exercice_units_+', to='tracker.ExerciseUnit'),
        ),
    ]
