# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-20 07:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0007_auto_20171020_0832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, help_text='Beschreibung.', max_length=500),
        ),
    ]
