# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-22 18:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0016_auto_20171022_1909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainunit',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
