# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-17 09:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0020_auto_20171117_0907'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainunit',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
