# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-26 19:08
from __future__ import unicode_literals

from django.db import migrations, models

import tracker.models.models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0026_profile_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='achievement',
            name='achievement_image',
            field=models.ImageField(blank=True, null=True, upload_to=tracker.models.models.get_image_path),
        ),
    ]
