# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-27 16:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0027_achievement_achievement_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='friends',
            field=models.ManyToManyField(blank=True, null=True, to='tracker.Profile'),
        ),
    ]
