# Generated by Django 2.0.1 on 2018-01-18 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0039_gymprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gym',
            name='members',
        ),
        migrations.RemoveField(
            model_name='gymprofile',
            name='gym',
        ),
        migrations.AddField(
            model_name='gymprofile',
            name='members',
            field=models.ManyToManyField(blank=True, to='tracker.UserProfile'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='gym',
            field=models.ManyToManyField(blank=True, to='tracker.GymProfile'),
        ),
        migrations.DeleteModel(
            name='Gym',
        ),
    ]
