# Generated by Django 2.0.1 on 2018-08-23 19:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0001_initial'),
        ('tracker', '0004_auto_20180823_2117'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='tracking_data',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.UserTrackingProfile'),
        ),
        migrations.AddField(
            model_name='gymprofile',
            name='members',
            field=models.ManyToManyField(blank=True, to='main.UserProfile'),
        ),
    ]
