# Generated by Django 2.0.6 on 2018-08-26 09:51

import app_main.models.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='GymProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('bio', models.TextField(blank=True, help_text='Beschreibung.', max_length=1000)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to=app_main.models.models.get_image_path)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('bio', models.TextField(blank=True, help_text='Beschreibung.', max_length=1000)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to=app_main.models.models.get_image_path)),
                ('date_of_birth', models.DateField()),
                ('rfid_tag', models.CharField(blank=True, max_length=10, null=True, verbose_name='RFID')),
                ('gym', models.ManyToManyField(blank=True, to='app_main.GymProfile')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='gymprofile',
            name='members',
            field=models.ManyToManyField(blank=True, to='app_main.UserProfile'),
        ),
    ]
