# Generated by Django 2.0.6 on 2018-08-26 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_achievements', '0001_initial'),
        ('app_main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='achievements',
            field=models.ManyToManyField(blank=True, to='app_achievements.Achievement'),
        ),
    ]
