# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-19 17:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='training_units',
            field=models.ManyToManyField(blank=True, null=True, related_name='_user_training_units_+', to='tracker.TrainUnit'),
        ),
    ]
