# Generated by Django 2.0.1 on 2018-03-01 15:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='active_set',
            new_name='_active_set',
        ),
        migrations.AddField(
            model_name='set',
            name='last_update',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
