# Generated by Django 2.0.1 on 2018-05-29 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientConnection',
            fields=[
                ('name', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('rfid_tag', models.CharField(max_length=10, verbose_name='RFID')),
            ],
        ),
    ]
