# Generated by Django 2.0.1 on 2018-08-23 19:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '__first__'),
        ('auth', '0009_alter_user_last_name_max_length'),
        ('tracker', '0003_exerciseunit_equipment'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTrackingProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('_pr_active_set', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tracker.Set')),
            ],
        ),
        migrations.RemoveField(
            model_name='achievement',
            name='user',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='user',
        ),
        migrations.RemoveField(
            model_name='gymprofile',
            name='members',
        ),
        migrations.RemoveField(
            model_name='gymprofile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='_pr_active_set',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='achievements',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='gym',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.AlterField(
            model_name='equipment',
            name='gym',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='gym', to='main.GymProfile'),
        ),
        migrations.AlterField(
            model_name='trainunit',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.UserTrackingProfile'),
        ),
        migrations.DeleteModel(
            name='Achievement',
        ),
        migrations.DeleteModel(
            name='Activity',
        ),
        migrations.DeleteModel(
            name='GymProfile',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
