# Generated by Django 2.0.1 on 2018-03-04 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_auto_20180304_1744'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='_pr_active_set',
            new_name='active_set',
        ),
    ]
