# Generated by Django 2.0.1 on 2018-03-04 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_auto_20180304_1751'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='active_set',
            new_name='_pr_active_set',
        ),
    ]
