# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-19 20:37
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_auto_20171019_1845'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='training_units',
        ),
        migrations.AlterField(
            model_name='trainunit',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
