# Generated by Django 2.0.1 on 2018-04-18 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0005_auto_20180304_1753'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='set',
            options={'ordering': ['-date_time']},
        ),
        migrations.AddField(
            model_name='exerciseunit',
            name='sets',
            field=models.ManyToManyField(blank=True, related_name='_exerciseunit_sets_+', to='tracker.Set'),
        ),
    ]
