# Generated by Django 2.0.1 on 2018-04-18 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0006_auto_20180418_1706'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exerciseunit',
            name='sets',
        ),
    ]
