# Generated by Django 2.0.1 on 2018-04-20 05:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0008_remove_trainunit_exercise_units'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exerciseunit',
            name='time_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
