# Generated by Django 2.0.1 on 2018-04-24 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0010_auto_20180420_0713'),
    ]

    operations = [
        migrations.CreateModel(
            name='MuscleGroup',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
        ),
        migrations.AlterModelOptions(
            name='exerciseunit',
            options={'ordering': ['-time_date']},
        ),
        migrations.AlterModelOptions(
            name='trainunit',
            options={'ordering': ['-start_time_date']},
        ),
        migrations.AddField(
            model_name='exercise',
            name='gimprove_system',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='set',
            name='auto_tracking',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='muscle',
            name='muscle_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tracker.MuscleGroup'),
        ),
    ]
