# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-22 17:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0010_auto_20171022_1737'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trainunit',
            old_name='id',
            new_name='nr',
        ),
    ]
