# Generated by Django 2.0.1 on 2018-04-24 17:15

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0011_auto_20180424_1906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='gimprove_system',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='muscle',
            name='muscle_group',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.DO_NOTHING, to='tracker.MuscleGroup'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='set',
            name='auto_tracking',
            field=models.BooleanField(default=False),
        ),
    ]
