# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-23 07:45
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0017_auto_20171022_1909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainunit',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
    ]
