# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-17 09:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0019_auto_20171117_0840'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exerciseunit',
            old_name='end_time_date',
            new_name='time_date',
        ),
        migrations.RemoveField(
            model_name='exerciseunit',
            name='start_time_date',
        ),
    ]
