# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-26 17:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0022_achievement'),
    ]

    operations = [
        migrations.AddField(
            model_name='achievement',
            name='description',
            field=models.TextField(blank=True, help_text='What did the user do to achieve it?', max_length=500, null=True),
        ),
    ]
