# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-26 17:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0024_profile_achievements'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='achievement',
            name='id',
        ),
        migrations.AlterField(
            model_name='achievement',
            name='name',
            field=models.CharField(help_text='Insert the name of the achievement here.', max_length=100, primary_key=True, serialize=False),
        ),
    ]
