# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-27 16:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0029_auto_20171127_1635'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friendship',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='friendship',
            name='friend',
        ),
        migrations.AddField(
            model_name='profile',
            name='friends',
            field=models.ManyToManyField(blank=True, null=True, to='tracker.Profile'),
        ),
        migrations.DeleteModel(
            name='Friendship',
        ),
    ]
