# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-22 13:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0036_auto_20171215_0924'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='achievements',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='gym',
        ),
    ]
