# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-22 13:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0037_auto_20171222_1354'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('profile_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tracker.Profile')),
                ('date_of_birth', models.DateField()),
                ('achievements', models.ManyToManyField(blank=True, to='tracker.Achievement')),
                ('gym', models.ManyToManyField(blank=True, to='tracker.Gym')),
            ],
            bases=('tracker.profile',),
        ),
    ]
