# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-22 14:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0038_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='GymProfile',
            fields=[
                ('profile_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tracker.Profile')),
                ('gym', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tracker.Gym')),
            ],
            bases=('tracker.profile',),
        ),
    ]
