# Generated by Django 2.0.6 on 2018-08-26 09:51

import app_main.models.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('name', models.CharField(help_text='Insert the name of the achievement here.', max_length=100, primary_key=True, serialize=False)),
                ('description', models.TextField(blank=True, help_text='What did the user do to achieve it?', max_length=500, null=True)),
                ('achievement_image', models.ImageField(blank=True, null=True, upload_to=app_main.models.models.get_image_path)),
                ('user', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
